import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CoverCycle,coverCandidates,initialMapCamera} from '../lib/coin-cover-cycle.ts';
import {coinPlaces,mapCoinImage,markerGeometry} from '../lib/coin-map.ts';
const atlas=JSON.parse(readFileSync(new URL('../public/data/atlas.json',import.meta.url)));
test('default 80% span never overrides an explicit camera',()=>{assert.ok(Math.abs(2**(4.65-initialMapCamera().zoom)-.8)<1e-12);const saved={center:[66,39],zoom:9};assert.equal(initialMapCamera(saved),saved)});
test('candidates use matched covers only, stable order, exclude missing cutouts and deduplicate',()=>{const groups=coinPlaces(atlas.families,atlas.specimens,atlas.places);const members=groups.find(g=>g.members.length>3).members;const paths=coverCandidates(members);assert.deepEqual(coverCandidates([...members].reverse()),paths);assert.deepEqual(coverCandidates([members[0],members[0],{...members[0],image:null}]),[mapCoinImage(members[0].image).path]);assert.deepEqual(coverCandidates([members[0]]),[mapCoinImage(members[0].image).path]);const slot=markerGeometry({x:0,y:0},true,false,members.length,0,members[0].image,members);for(const m of members){const g=markerGeometry({x:0,y:0},true,false,members.length,0,m.image);assert.ok(slot.width>=g.width&&slot.height>=g.height)}});
test('cycle pauses, survives redraws, fixes selection, skips failed loads, and cleans removed entries',()=>{const c=new CoverCycle();c.sync('city',['a','b','c'],'a');assert.equal(c.advance('city',9000,false),undefined);c.sync('city',['a','b','c'],'a');assert.equal(c.advance('city',5000,true),undefined);assert.equal(c.advance('city',1000,false),'b');assert.equal(c.loaded('city','b',false),false);assert.equal(c.advance('city',10000,false),'c');assert.equal(c.loaded('city','c',true),true);assert.equal(c.sync('city',['a','c'],'a','a'),'a');assert.equal(c.advance('city',10000,true),undefined);c.retain(new Set());assert.equal(c.states.size,0);assert.equal(c.loaded('city','c',true),false);c.sync('one',['a'],'a');assert.equal(c.advance('one',20000,false),undefined);c.clear();assert.equal(c.states.size,0)});
