'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {Search,SlidersHorizontal,X,ExternalLink,MapPin,BookOpen,Images,GitCompareArrows,ChevronRight,Database,Maximize2} from 'lucide-react';
import TerrainMap from '@/components/atlas/terrain-map';
import {overlaps,type Atlas,type Family,type Specimen,type Variant} from '@/lib/atlas';

type View='atlas'|'catalogue'|'research';
type SourceGroup={key:string;source:string;path:string;specimens:Specimen[]};

function OutLink({url,children}:{url:string;children:ReactNode}){return <a className="out-link" href={url} target="_blank" rel="noreferrer">{children}<ExternalLink size={12}/></a>}
function sourceName(s:{label:string;url:string}){
 if(/^Zeno\s/i.test(s.label)||s.url.includes('zeno.ru'))return 'Zeno';
 if(s.url.includes('cngcoins.com'))return 'CNG';
 if(s.url.includes('numista.com'))return 'Numista';
 if(s.url.includes('sogdcoins.'))return 'Coins of Central Asia';
 if(s.url.includes('bactrianumis'))return 'Bactrianumis';
 if(/album|sarc/i.test(s.label+s.url))return 'Stephen Album';
 try{return new URL(s.url).hostname.replace(/^www\./,'')||s.label}catch{return s.label||'Other source'}
}
function visibleFacet(x:string){return !x.startsWith('#503')&&!x.startsWith('Zeno source group')&&!/record-level visual review/i.test(x)}
function sourcePathLabel(s:Specimen){
 const p=s.sourcePath||[];
 if(p.length)return p.map(x=>x.title).join(' › ');
 return s.catalogue||'Unclassified source record';
}

export default function Home(){
 const [data,setData]=useState<Atlas|null>(null),[loadError,setLoadError]=useState(false);
 const [view,setView]=useState<View>('atlas'),[selectedId,setSelectedId]=useState<string|null>(null),[focus,setFocus]=useState(0);
 const [query,setQuery]=useState(''),[region,setRegion]=useState('all'),[polity,setPolity]=useState('all'),[city,setCity]=useState('all'),[familyFilter,setFamilyFilter]=useState('all'),[sourceFilter,setSourceFilter]=useState('all'),[featureFilter,setFeatureFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all');
 const [year,setYear]=useState(750),[allPeriods,setAllPeriods]=useState(true),[filtersOpen,setFiltersOpen]=useState(false);
 const [variant,setVariant]=useState('all'),[facet,setFacet]=useState('all');
 const [lightbox,setLightbox]=useState<Specimen|null>(null),[imageIndex,setImageIndex]=useState(0),[compareIds,setCompareIds]=useState<string[]>([]);
 const [catalogueMode,setCatalogueMode]=useState<'atlas'|'source'>('atlas'),[catalogueFamily,setCatalogueFamily]=useState<string|null>(null),[catalogueSource,setCatalogueSource]=useState<string|null>(null),[catalogueQuery,setCatalogueQuery]=useState('');
 useEffect(()=>{fetch('/data/atlas.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setData(d as Atlas)).catch(()=>setLoadError(true))},[]);
 useEffect(()=>{if(!data)return;const p=new URLSearchParams(window.location.hash.replace(/^#/,''));const v=p.get('view') as View|null;if(v&&['atlas','catalogue','research'].includes(v))setView(v);const f=p.get('family');if(f&&data.families.some(x=>x.id===f)){setSelectedId(f);setCatalogueFamily(f)}const src=p.get('source');if(src){setCatalogueMode('source');setCatalogueSource(src);setView('catalogue')}const rec=p.get('record');if(rec){const hit=data.specimens.find(x=>x.id===rec);if(hit){setLightbox(hit);setImageIndex(0);setSelectedId(hit.familyId)}}},[data]);
 useEffect(()=>{if(!data)return;const p=new URLSearchParams();if(view!=='atlas')p.set('view',view);if(selectedId)p.set('family',selectedId);if(view==='catalogue'&&catalogueMode==='source'&&catalogueSource)p.set('source',catalogueSource);if(lightbox)p.set('record',lightbox.id);const next=p.toString();history.replaceState(null,'',next?`#${next}`:window.location.pathname)},[view,selectedId,catalogueMode,catalogueSource,lightbox,data]);

 const specimensByFamily=useMemo(()=>{const m=new Map<string,Specimen[]>();for(const s of data?.specimens||[]){const a=m.get(s.familyId)||[];a.push(s);m.set(s.familyId,a)}return m},[data]);
 const variantsByFamily=useMemo(()=>{const m=new Map<string,Variant[]>();for(const v of data?.variants||[]){const a=m.get(v.familyId)||[];a.push(v);m.set(v.familyId,a)}return m},[data]);
 const sources=useMemo<string[]>(()=>Array.from(new Set((data?.specimens||[]).map(s=>s.sourceName||sourceName(s.sources[0])))).sort(),[data]);
 const features=useMemo<string[]>(()=>Array.from(new Set((data?.specimens||[]).flatMap(s=>s.facets.filter(visibleFacet)))).sort(),[data]);
 const regions=useMemo<string[]>(()=>Array.from(new Set((data?.families||[]).map(f=>f.region))).sort(),[data]);
 const polities=useMemo<string[]>(()=>Array.from(new Set((data?.families||[]).map(f=>f.polity).filter((x):x is string=>Boolean(x)))).sort(),[data]);
 const researchStatuses=useMemo<string[]>(()=>Array.from(new Set((data?.families||[]).map(f=>f.status))).sort(),[data]);
 const filteredFamilies=useMemo(()=>{
  if(!data)return[];const q=query.trim().toLowerCase();
  return data.families.filter(f=>{
   const ss=specimensByFamily.get(f.id)||[];const placeId=f.anchor?.placeId||null;
   const sourceOk=sourceFilter==='all'||ss.some(s=>(s.sourceName||sourceName(s.sources[0]))===sourceFilter);
   const featureOk=featureFilter==='all'||ss.some(s=>s.facets.includes(featureFilter));
   const vv=variantsByFamily.get(f.id)||[];const qOk=!q||[f.title,f.zh,f.region,f.dateLabel,f.description,f.legend||'',...vv.flatMap(v=>[v.title,v.reference,v.description,...v.facets]),...ss.flatMap(s=>[s.title,s.catalogue,s.description,s.sourceRecordId||'',sourcePathLabel(s),...s.sources.map(x=>x.label),...s.facets])].join(' ').toLowerCase().includes(q);
   return (region==='all'||f.region===region)&&(polity==='all'||f.polity===polity)&&(city==='all'||placeId===city)&&(familyFilter==='all'||f.id===familyFilter)&&(statusFilter==='all'||f.status===statusFilter)&&overlaps(f.start,f.end,allPeriods?null:year)&&sourceOk&&featureOk&&qOk;
  })
 },[data,query,region,polity,city,familyFilter,sourceFilter,featureFilter,statusFilter,year,allPeriods,specimensByFamily,variantsByFamily]);
 const selected=data?.families.find(f=>f.id===selectedId)||null;
 const selectedSpecimens=selected?specimensByFamily.get(selected.id)||[]:[];
 const selectedVariants=selected?data?.variants.filter(v=>v.familyId===selected.id)||[]:[];
 const selectedFacets:string[]=Array.from(new Set(selectedSpecimens.flatMap(s=>s.facets.filter(visibleFacet))));
 const shownSpecimens=selectedSpecimens.filter(s=>(variant==='all'||(variant==='unassigned'?s.variantId===null:s.variantId===variant))&&(facet==='all'||s.facets.includes(facet)));
 const selectedPlace=selected?.anchor?data?.places.find(p=>p.id===selected.anchor?.placeId):null;
 const compare=data?.specimens.filter(s=>compareIds.includes(s.id))||[];
 const sourceGroups=useMemo<SourceGroup[]>(()=>{if(!data)return[];const m=new Map<string,SourceGroup>();for(const s of data.specimens){const primary=s.sources[0];const source=s.sourceName||(primary?sourceName(primary):'Unknown');const path=source==='Zeno'?sourcePathLabel(s):(s.catalogue||source);const key=source+'|'+path;const g=m.get(key)||{key,source,path,specimens:[]};g.specimens.push(s);m.set(key,g)}return [...m.values()].sort((a,b)=>a.source.localeCompare(b.source)||a.path.localeCompare(b.path))},[data]);
 const filteredFamilyIds=useMemo(()=>new Set(filteredFamilies.map(f=>f.id)),[filteredFamilies]);
 const catalogueSourceGroups=useMemo(()=>sourceGroups.map(g=>({...g,specimens:g.specimens.filter(s=>filteredFamilyIds.has(s.familyId))})).filter(g=>g.specimens.length>0),[sourceGroups,filteredFamilyIds]);
 const sourceGroup=catalogueSourceGroups.find(g=>g.key===catalogueSource)||null;
 const relatedMatches=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return data.relatedRecords.filter(r=>[r.sourceRecordId,r.title,r.reviewStatus,r.reason,r.leafCategoryTitle,...r.sourcePath.map(x=>x.title)].join(' ').toLowerCase().includes(q))},[data,query]);
 const quickSpecimens=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return data.specimens.filter(s=>filteredFamilyIds.has(s.familyId)&&[s.title,s.sourceRecordId||'',s.catalogue,s.description,sourcePathLabel(s),...s.sources.map(x=>x.label),...s.facets].join(' ').toLowerCase().includes(q)).slice(0,6)},[data,query,filteredFamilyIds]);

 function chooseFamily(id:string){setSelectedId(id);setVariant('all');setFacet('all');setFocus(x=>x+1);if(view==='catalogue')setCatalogueFamily(id)}
 function openSpecimen(s:Specimen){setLightbox(s);setImageIndex(0)}
 function toggleCompare(id:string){setCompareIds(xs=>xs.includes(id)?xs.filter(x=>x!==id):xs.length>=3?[xs[1],xs[2],id]:[...xs,id])}
 function clearFilters(){setQuery('');setRegion('all');setPolity('all');setCity('all');setFamilyFilter('all');setSourceFilter('all');setFeatureFilter('all');setStatusFilter('all');setAllPeriods(true)}
 const imageCount=data?.specimens.reduce((n,s)=>n+s.images.length,0)||0;
 if(!data)return <main className="boot-state"><div><Database size={30}/><p>{loadError?'Catalogue could not load. Please reload.':'Loading Central Asian Square-Hole Coinage Atlas…'}</p></div></main>;

 return <main className="atlas-app">
  <header className="app-header"><button className="brand-button" onClick={()=>setView('atlas')}><span className="brand-mark">◈</span><span><strong>CENTRAL ASIAN SQUARE-HOLE COINAGE ATLAS</strong><small>中亚方孔钱地图与图像资料库</small></span></button><nav>{([['atlas','Atlas'],['catalogue','Catalogue'],['research','Research']] as [View,string][]).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="header-stats"><span>{data.families.length} families</span><b>·</b><span>{data.specimens.length} records</span></div></header>

  {view==='atlas'&&<section className="atlas-screen">
   <TerrainMap data={data} families={filteredFamilies} selected={selected} onSelect={chooseFamily} year={allPeriods?null:year} focus={focus}/>
   <div className="atlas-search-panel"><div className="atlas-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索类型、铭文、编号、来源…"/><button aria-label="Filters" className={filtersOpen?'active':''} onClick={()=>setFiltersOpen(x=>!x)}><SlidersHorizontal size={16}/></button>{(query||region!=='all'||polity!=='all'||city!=='all'||familyFilter!=='all'||sourceFilter!=='all'||featureFilter!=='all'||statusFilter!=='all'||!allPeriods)&&<button aria-label="Clear filters" onClick={clearFilters}><X size={15}/></button>}</div>
    {filtersOpen&&<div className="filter-grid"><label>历史地区<select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">全部地区</option>{regions.map(r=><option key={r} value={r}>{r}</option>)}</select></label><label>政权 / 地方体系<select value={polity} onChange={e=>setPolity(e.target.value)}><option value="all">全部政权与体系</option>{polities.map(p=><option key={p} value={p}>{p}</option>)}</select></label><label>城市 / 展示锚点<select value={city} onChange={e=>setCity(e.target.value)}><option value="all">全部位置</option>{data.places.map(p=><option key={p.id} value={p.id}>{p.name} · {p.zh}</option>)}</select></label><label>类型家族<select value={familyFilter} onChange={e=>setFamilyFilter(e.target.value)}><option value="all">全部家族</option>{data.families.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select></label><label>来源<select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">全部来源</option>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label>研究状态<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option>{researchStatuses.map(s=><option key={s}>{s}</option>)}</select></label>{features.length>0&&<label className="filter-wide">铭文 / Tamgha / 特征<select value={featureFilter} onChange={e=>setFeatureFilter(e.target.value)}><option value="all">全部已标注特征</option>{features.map(f=><option key={f}>{f}</option>)}</select></label>}</div>}
    <div className="filter-result-line"><strong>{filteredFamilies.length}</strong> families · <strong>{filteredFamilies.reduce((n,f)=>n+(specimensByFamily.get(f.id)?.length||0),0)}</strong> records{filteredFamilies.some(f=>!f.anchor)&&<span> · {filteredFamilies.filter(f=>!f.anchor).length} families 暂无地图坐标</span>}</div>
    {(query||familyFilter!=='all')&&<div className="quick-results">{filteredFamilies.slice(0,5).map(f=><button key={f.id} onClick={()=>chooseFamily(f.id)}><img src={f.image} alt=""/><span><strong>{f.title}</strong><small>{f.region} · {specimensByFamily.get(f.id)?.length||0} records</small></span><ChevronRight size={14}/></button>)}{quickSpecimens.map(s=><button key={'record-'+s.id} onClick={()=>openSpecimen(s)}><img src={s.images[0]?.path} alt=""/><span><strong>{s.sourceRecordId||s.id}</strong><small>{s.title} · {s.sourceName||sourceName(s.sources[0])}</small></span><Maximize2 size={13}/></button>)}{relatedMatches.length>0&&<button onClick={()=>{setCatalogueQuery(query);setCatalogueMode('source');setCatalogueSource('__related__');setView('catalogue')}}><span className="related-search-icon">R</span><span><strong>相关 / held / excluded</strong><small>{relatedMatches.length} 条来源记录匹配当前搜索</small></span><ChevronRight size={14}/></button>}</div>}
   </div>
   <div className="timeline-floating"><button className={allPeriods?'active':''} onClick={()=>setAllPeriods(true)}>全部时期</button><input aria-label="Issue date filter" type="range" min="200" max="1650" step="10" value={year} onChange={e=>{setYear(Number(e.target.value));setAllPeriods(false)}}/><strong>{allPeriods?'All periods':`${year} CE`}</strong></div>
   {selected&&<FamilyDrawer family={selected} placeName={selectedPlace?.name||null} specimens={shownSpecimens} allSpecimens={selectedSpecimens} variants={selectedVariants} facets={selectedFacets} variant={variant} facet={facet} setVariant={setVariant} setFacet={setFacet} onClose={()=>setSelectedId(null)} onCatalogue={()=>{setCatalogueMode('atlas');setCatalogueFamily(selected.id);setView('catalogue')}} onOpen={openSpecimen} onCompare={toggleCompare} compareIds={compareIds}/>}
  </section>}

  {view==='catalogue'&&<section className="catalogue-page"><aside className="catalogue-tree"><div className="catalogue-title"><BookOpen size={18}/><div><strong>Catalogue</strong><small>纲目与来源目录 · 当前 Atlas 筛选同步</small></div></div><div className="catalogue-switch"><button className={catalogueMode==='atlas'?'active':''} onClick={()=>setCatalogueMode('atlas')}>Atlas 纲目</button><button className={catalogueMode==='source'?'active':''} onClick={()=>setCatalogueMode('source')}>来源目录</button></div><div className="catalogue-search"><Search size={14}/><input value={catalogueQuery} onChange={e=>setCatalogueQuery(e.target.value)} placeholder="搜索名称、编号、来源…"/></div>{catalogueMode==='atlas'?<div className="tree-scroll">{regions.map(r=>{const cq=catalogueQuery.trim().toLowerCase();const fs=filteredFamilies.filter(f=>f.region===r&&(!cq||[f.title,f.zh,f.description,f.polity||'',...(specimensByFamily.get(f.id)||[]).flatMap(s=>[s.title,s.sourceRecordId||'',s.catalogue])].join(' ').toLowerCase().includes(cq)));if(!fs.length)return null;const ps=Array.from(new Set(fs.map(f=>f.polity||'Unresolved')));return <details key={r} open={fs.some(f=>f.id===catalogueFamily)}><summary>{r}<span>{fs.length}</span></summary>{ps.map(p=><details className="tree-subgroup" key={p} open={fs.some(f=>f.polity===p&&f.id===catalogueFamily)}><summary>{p}<span>{fs.filter(f=>(f.polity||'Unresolved')===p).length}</span></summary>{fs.filter(f=>(f.polity||'Unresolved')===p).map(f=><button key={f.id} className={catalogueFamily===f.id?'active':''} onClick={()=>{setCatalogueFamily(f.id);setCatalogueSource(null);setSelectedId(f.id)}}><span>{f.title}</span><small>{specimensByFamily.get(f.id)?.length||0}</small></button>)}</details>)}</details>})}</div>:<div className="tree-scroll"><button className={'special-tree-node '+(catalogueSource==='__related__'?'active':'')} onClick={()=>{setCatalogueSource('__related__');setCatalogueFamily(null)}}><span>相关 / held / excluded</span><small>{data.relatedRecords.length}</small></button>{sources.map(src=>{const cq=catalogueQuery.trim().toLowerCase();const gs=catalogueSourceGroups.filter(g=>g.source===src&&(!cq||[g.source,g.path,...g.specimens.flatMap(s=>[s.title,s.sourceRecordId||''])].join(' ').toLowerCase().includes(cq)));if(!gs.length)return null;return <details key={src} open={gs.some(g=>g.key===catalogueSource)}><summary>{src}<span>{gs.reduce((n,g)=>n+g.specimens.length,0)}</span></summary>{gs.map(g=><button key={g.key} className={catalogueSource===g.key?'active':''} onClick={()=>{setCatalogueSource(g.key);setCatalogueFamily(null)}}><span>{g.path}</span><small>{g.specimens.length}</small></button>)}</details>})}</div>}</aside>
   <div className="catalogue-content">{catalogueMode==='atlas'?<CatalogueFamily data={data} family={data.families.find(f=>f.id===catalogueFamily)||data.families[0]} specimensByFamily={specimensByFamily} onOpen={openSpecimen} onCompare={toggleCompare} compareIds={compareIds}/>:catalogueSource==='__related__'?<RelatedCatalogue data={data} query={catalogueQuery}/>:sourceGroup?<SourceCatalogueGroup group={sourceGroup} data={data} onOpen={openSpecimen} onFamily={id=>{setCatalogueMode('atlas');setCatalogueFamily(id);setSelectedId(id)}}/>:<EmptyCatalogue/>}</div>
  </section>}

  {view==='research'&&<ResearchView data={data} imageCount={imageCount} sources={sources}/>}

  {compare.length>0&&<CompareTray items={compare} data={data} onRemove={toggleCompare} onClear={()=>setCompareIds([])} onOpen={openSpecimen}/>}
  {lightbox&&<SpecimenLightbox specimen={lightbox} family={data.families.find(f=>f.id===lightbox.familyId)||null} index={imageIndex} setIndex={setImageIndex} onClose={()=>setLightbox(null)}/>}
 </main>
}

function FamilyDrawer({family,placeName,specimens,allSpecimens,variants,facets,variant,facet,setVariant,setFacet,onClose,onCatalogue,onOpen,onCompare,compareIds}:{family:Family;placeName:string|null;specimens:Specimen[];allSpecimens:Specimen[];variants:Variant[];facets:string[];variant:string;facet:string;setVariant:(x:string)=>void;setFacet:(x:string)=>void;onClose:()=>void;onCatalogue:()=>void;onOpen:(s:Specimen)=>void;onCompare:(id:string)=>void;compareIds:string[]}){
 const activeVariant=variants.find(v=>v.id===variant)||null;
 return <aside className="family-drawer"><div className="drawer-head"><span>TYPE FAMILY / 类型家族</span><div className="drawer-head-actions"><button onClick={onCatalogue}><BookOpen size={15}/>目录</button><button onClick={onClose} aria-label="Close details"><X size={18}/></button></div></div><div className="drawer-scroll"><h1>{family.title}</h1><p className="family-zh">{family.zh}</p><div className="family-meta"><span>{family.dateLabel}</span><span>{family.region}</span>{family.polity&&<span>{family.polity}</span>}<span>{family.status}</span></div><p>{family.description}</p>{family.anchor&&<div className="evidence-note"><MapPin size={16}/><div><strong>{placeName||family.anchor.placeId}</strong><small>{family.anchor.role}</small><p>{family.anchor.note}</p></div></div>}{family.question&&<div className="question-note">{family.question}</div>}
 <div className="drawer-section-title"><div><Images size={15}/><strong>图库</strong></div><span>{allSpecimens.length} records · {allSpecimens.reduce((n,s)=>n+s.images.length,0)} images</span></div><div className="drawer-filters"><select value={variant} onChange={e=>setVariant(e.target.value)}><option value="all">全部 catalogue groups</option>{variants.map(v=><option key={v.id} value={v.id}>{v.title} ({allSpecimens.filter(s=>s.variantId===v.id).length})</option>)}{allSpecimens.some(s=>s.variantId===null)&&<option value="unassigned">分组待定</option>}</select>{facets.length>0&&<select value={facet} onChange={e=>setFacet(e.target.value)}><option value="all">全部铭文 / Tamgha / 特征</option>{facets.map(f=><option key={f}>{f}</option>)}</select>}</div>{activeVariant&&<div className="group-context"><strong>{activeVariant.title}</strong><span>{activeVariant.status}</span>{activeVariant.reference&&<small>{activeVariant.reference}</small>}<p>{activeVariant.description}</p></div>}<div className="drawer-gallery">{specimens.map(s=><SpecimenTile key={s.id} s={s} onOpen={onOpen} onCompare={onCompare} comparing={compareIds.includes(s.id)}/>)}</div>{!specimens.length&&<p className="empty-state">当前分组没有记录。</p>}
 <details className="research-block"><summary><BookOpen size={15}/>研究、铭文与来源</summary>{family.legend&&<><h3>铭文 / Inscription</h3><p className="inscription">{family.legend}</p>{family.legendNote&&<p>{family.legendNote}</p>}</>}<h3>研究与目录</h3>{family.publications.map(p=><div className="publication" key={p.url}><OutLink url={p.url}>{p.title}</OutLink><small>{p.role}</small></div>)}</details></div></aside>
}

function SpecimenTile({s,onOpen,onCompare,comparing}:{s:Specimen;onOpen:(s:Specimen)=>void;onCompare:(id:string)=>void;comparing:boolean}){const primary=s.sources[0];return <article className="specimen-tile"><button className="specimen-image" onClick={()=>onOpen(s)}><img src={s.images[0]?.path} alt={s.title}/><span><Maximize2 size={12}/>原图</span></button><div className="specimen-copy"><strong>{s.title}</strong><small>{[s.weightG!=null?`${s.weightG} g`:null,s.diameterMm!=null?`${s.diameterMm} mm`:null].filter(Boolean).join(' · ')||'尺寸未记录'}</small><small className="source-badge">{s.sourceName||(primary?sourceName(primary):'来源待整理')} · {s.sourceRecordId||s.id}</small><p>{s.catalogue}</p><div className="tile-actions"><button className={comparing?'active':''} onClick={()=>onCompare(s.id)}><GitCompareArrows size={13}/>{comparing?'已加入':'对比'}</button>{(s.sourceRecordUrl||primary?.url)&&<OutLink url={s.sourceRecordUrl||primary!.url}>来源</OutLink>}</div></div></article>}

function CatalogueFamily({data,family,specimensByFamily,onOpen,onCompare,compareIds}:{data:Atlas;family:Family;specimensByFamily:Map<string,Specimen[]>;onOpen:(s:Specimen)=>void;onCompare:(id:string)=>void;compareIds:string[]}){const ss=specimensByFamily.get(family.id)||[];const vs=data.variants.filter(v=>v.familyId===family.id);return <><div className="catalogue-breadcrumb">Atlas 纲目 / {family.region} / {family.title}</div><div className="catalogue-hero"><img src={family.image} alt=""/><div><span className="eyebrow">{family.status}</span><h1>{family.title}</h1><p className="family-zh">{family.zh}</p><p>{family.description}</p><div className="family-meta"><span>{family.dateLabel}</span><span>{ss.length} records</span><span>{ss.reduce((n,s)=>n+s.images.length,0)} images</span></div></div></div>{family.question&&<div className="question-note wide">{family.question}</div>}<h2 className="catalogue-heading">Catalogue groups / 目录分组</h2><div className="group-list">{vs.map(v=><details key={v.id}><summary><span><strong>{v.title}</strong><small>{v.description}</small></span><b>{ss.filter(s=>s.variantId===v.id).length}</b></summary><div className="catalogue-gallery">{ss.filter(s=>s.variantId===v.id).map(s=><SpecimenTile key={s.id} s={s} onOpen={onOpen} onCompare={onCompare} comparing={compareIds.includes(s.id)}/>)}</div></details>)}{ss.some(s=>s.variantId===null)&&<details><summary><span><strong>Unassigned / 待定分组</strong><small>来源记录保留，尚未强制归入目录分组。</small></span><b>{ss.filter(s=>!s.variantId).length}</b></summary><div className="catalogue-gallery">{ss.filter(s=>!s.variantId).map(s=><SpecimenTile key={s.id} s={s} onOpen={onOpen} onCompare={onCompare} comparing={compareIds.includes(s.id)}/>)}</div></details>}</div></>}

function SourceCatalogueGroup({group,data,onOpen,onFamily}:{group:SourceGroup;data:Atlas;onOpen:(s:Specimen)=>void;onFamily:(id:string)=>void}){return <><div className="catalogue-breadcrumb">来源目录 / {group.source} / {group.path}</div><h1>{group.path}</h1><p>这里展示来源侧记录及其 Atlas 去向。来源分类不会因 Atlas 的研究重组而被覆盖。</p><div className="source-group-summary"><span>{group.source}</span><strong>{group.specimens.length} records</strong></div><div className="source-record-list">{group.specimens.map(s=>{const f=data.families.find(x=>x.id===s.familyId);return <article key={s.id}><button className="source-thumb" onClick={()=>onOpen(s)}><img src={s.images[0]?.path} alt=""/></button><div><strong>{s.sourceRecordId||s.id}</strong><p>{s.title}</p>{s.sourcePath&&s.sourcePath.length>0&&<small>{s.sourcePath.map(x=>`${x.title} [${x.categoryId}]`).join(' › ')}</small>}<div className="source-record-actions"><button className="text-button" onClick={()=>onFamily(s.familyId)}>Atlas → {f?.title||s.familyId}</button>{s.sourceRecordUrl&&<OutLink url={s.sourceRecordUrl}>原始记录</OutLink>}</div></div></article>})}</div></>}

function RelatedCatalogue({data,query}:{data:Atlas;query:string}){const q=query.trim().toLowerCase();const records=data.relatedRecords.filter(r=>!q||[r.sourceRecordId,r.title,r.reviewStatus,r.reason,r.leafCategoryTitle,...r.sourcePath.map(x=>x.title)].join(' ').toLowerCase().includes(q));const groups=Array.from(new Set(records.map(r=>r.reviewStatus))).sort();return <><div className="catalogue-breadcrumb">来源目录 / related · held · excluded</div><h1>相关与暂缓资料</h1><p>这些记录仍属于研究资料层。它们没有进入主方孔钱计数，原始来源、分类路径和审查原因继续保留；状态不会触发原始资料删除。</p><div className="related-status-grid">{groups.map(g=><div key={g}><strong>{records.filter(r=>r.reviewStatus===g).length}</strong><span>{g}</span></div>)}</div><div className="related-list">{records.map(r=><article key={r.id}><div><strong>{r.sourceRecordId}</strong><span>{r.reviewStatus}</span></div><h3>{r.title.replace(/^#\d+ - /,'')}</h3>{r.sourcePath.length>0&&<small>{r.sourcePath.map(x=>`${x.title} [${x.categoryId}]`).join(' › ')}</small>}<p>{r.reason}</p><OutLink url={r.sourceUrl}>打开原始记录</OutLink></article>)}</div></>}

function EmptyCatalogue(){return <div className="empty-catalogue"><BookOpen size={28}/><h1>选择一个来源目录节点</h1><p>左侧来源树保留来源分类，右侧显示记录及其 Atlas 去向。</p></div>}

function ResearchView({data,imageCount,sources}:{data:Atlas;imageCount:number;sources:string[]}){const sourceCounts=Array.from(data.specimens.reduce((m,s)=>{const k=s.sourceName||sourceName(s.sources[0]);m.set(k,(m.get(k)||0)+1);return m},new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]);return <section className="research-page"><div className="research-hero"><span className="eyebrow">RESEARCH CORPUS · CURRENT EDITION</span><h1>来源可追溯的中亚方孔钱研究资料库</h1><p>当前版本把来源资料层、研究整理层和产品展示层分开。重复、未定归属和字段缺失可以保留；主 Atlas 的收录数量不作为稀有度判断。</p></div><div className="metrics-row"><div><strong>{data.families.length}</strong><span>families</span></div><div><strong>{data.variants.length}</strong><span>source / catalogue groups</span></div><div><strong>{data.specimens.length}</strong><span>specimen records</span></div><div><strong>{imageCount}</strong><span>images</span></div><div><strong>{sources.length}</strong><span>visible source systems</span></div><div><strong>{data.relatedRecords.length}</strong><span>related / held source records</span></div></div><div className="research-columns"><article><h2>来源资料层</h2><p>每条记录保留来源链接；Zeno 记录额外保留 source record ID 和原始 breadcrumb 分类路径。Atlas 的重新分类只增加研究关系，不覆盖来源树。</p><ul><li>原始来源记录和图片持续保留</li><li>related / held / excluded 不触发原始资料删除</li><li>same-image / same-specimen 关系只在有明确证据时增加</li></ul></article><article><h2>当前地图证据</h2><p>地图已经区分展示锚点、findspot / hoard evidence 与 area layers。没有可靠 polygon 的政权或类型继续显示在 Catalogue 与搜索中，不制造疆域或流通范围。</p><ul><li>{data.evidence.length} 条结构化空间证据</li><li>{data.areas.length} 个当前 area layer records</li><li>{data.families.filter(f=>!f.anchor).length} 个 family 暂无展示锚点</li></ul></article><article><h2>下一阶段</h2><p>一期优先完善 Atlas、Catalogue、来源与已有铭文/tamgha 检索。随后按地区和专题补充 IICAS、Smirnova、Kamyshev、Zeimal、考古报告、博物馆与拍卖资料。</p><ul><li>Learning：文字系统、铭文、tamgha 与真实钱币联动</li><li>Market：拍卖记录与履历，正式建设后每四个自然月增量更新</li><li>历史 GIS：只在来源支持时加入分期 polygon</li></ul></article></div><h2 className="research-section-title">Primary source records</h2><p className="research-footnote">以下数量表示当前主库记录的主要来源，不代表独立实物数量或稀有度。</p><div className="source-coverage-grid">{sourceCounts.map(([name,count])=><div key={name}><strong>{count}</strong><span>{name}</span></div>)}</div><h2 className="research-section-title">Source coverage snapshots</h2><div className="coverage-table"><table><thead><tr><th>Scope</th><th>Source snapshot</th><th>Observed</th><th>Status</th></tr></thead><tbody>{data.scopeCensus.map((c,i)=><tr key={`${c.categoryId}-${i}`}><td>{c.title}</td><td><OutLink url={c.url}>Zeno #{c.categoryId}</OutLink></td><td>{c.sourcePhotoCount}</td><td>source snapshot</td></tr>)}</tbody></table></div><div className="research-footnote">Lady Nana snapshot: {data.coverage.importedZenoRecords}/{data.coverage.zenoRecordCount} observed Zeno records imported · {data.coverage.images} images across its current source-linked corpus. Coverage snapshots describe captured source material, not global surviving populations.</div></section>}

function CompareTray({items,data,onRemove,onClear,onOpen}:{items:Specimen[];data:Atlas;onRemove:(id:string)=>void;onClear:()=>void;onOpen:(s:Specimen)=>void}){return <div className="compare-tray"><div className="compare-head"><strong><GitCompareArrows size={15}/>Compare · {items.length}/3</strong><button onClick={onClear}>清空</button></div><div className="compare-items">{items.map(s=>{const f=data.families.find(x=>x.id===s.familyId);return <article key={s.id}><button onClick={()=>onOpen(s)}><img src={s.images[0]?.path} alt=""/></button><div><strong>{s.title}</strong><small>{f?.title}</small><span>{s.weightG!=null?`${s.weightG} g`:'—'} · {s.diameterMm!=null?`${s.diameterMm} mm`:'—'}</span><span>{s.sourceName||(s.sources[0]?sourceName(s.sources[0]):'—')}</span></div><button className="remove-compare" onClick={()=>onRemove(s.id)}><X size={13}/></button></article>})}</div></div>}

function SpecimenLightbox({specimen,family,index,setIndex,onClose}:{specimen:Specimen;family:Family|null;index:number;setIndex:(n:number)=>void;onClose:()=>void}){const image=specimen.images[index]||specimen.images[0];return <div className="lightbox-overlay" role="dialog" aria-modal="true"><div className="specimen-modal"><button className="modal-close" onClick={onClose} aria-label="Close"><X size={20}/></button><div className="modal-image"><img src={image?.path} alt={specimen.title}/></div><div className="modal-info"><span className="eyebrow">{family?.title}</span><h1>{specimen.title}</h1><div className="family-meta"><span>{specimen.weightG!=null?`${specimen.weightG} g`:'weight unknown'}</span><span>{specimen.diameterMm!=null?`${specimen.diameterMm} mm`:'size unknown'}</span><span>{specimen.sourceRecordId||specimen.id}</span></div>{specimen.images.length>1&&<div className="image-strip">{specimen.images.map((im,i)=><button key={im.id} className={i===index?'active':''} onClick={()=>setIndex(i)}><img src={im.path} alt=""/></button>)}</div>}<p>{specimen.description}</p>{specimen.catalogue&&<div className="metadata-row"><strong>Catalogue</strong><span>{specimen.catalogue}</span></div>}{specimen.coinRole&&<div className="metadata-row"><strong>Coin role</strong><span>{specimen.coinRole}</span></div>}{specimen.findContextClaim&&<div className="metadata-row"><strong>Find context</strong><span>{typeof specimen.findContextClaim==='string'?specimen.findContextClaim:[specimen.findContextClaim.rawText,specimen.findContextClaim.status,specimen.findContextClaim.note].filter(Boolean).join(' · ')}</span></div>}{specimen.sourcePath&&specimen.sourcePath.length>0&&<div className="metadata-row"><strong>Source path</strong><span>{specimen.sourcePath.map(x=>`${x.title} [${x.categoryId}]`).join(' › ')}</span></div>}<div className="metadata-row"><strong>Image</strong><span>{image?.width} × {image?.height}px · {image?.credit||'credit pending'} · rights: {image?.rightsStatus||'unverified'}</span></div>{image?.sourceRecordUrl&&<div className="metadata-row"><strong>Image source</strong><span><OutLink url={image.sourceRecordUrl}>{image.sourceName||specimen.sourceName||'Source'} · {image.sourceRecordId||specimen.sourceRecordId||specimen.id}</OutLink>{image.sourceUrl&&image.sourceUrl!==image.sourceRecordUrl&&<> · <OutLink url={image.sourceUrl}>原始图片</OutLink></>}{image.rightsSourceUrl&&<> · <OutLink url={image.rightsSourceUrl}>权利说明</OutLink></>}</span></div>}<h3>Source records</h3><div className="modal-sources">{specimen.sources.map((s,i)=><OutLink key={s.url+i} url={s.url}>{sourceName(s)} · {s.label}</OutLink>)}</div>{specimen.facets.filter(visibleFacet).length>0&&<><h3>Inscription / tamgha / features</h3><div className="facet-chips">{specimen.facets.filter(visibleFacet).map(x=><span key={x}>{x}</span>)}</div></>}</div></div></div>}
