'use client';
import {useEffect,useMemo,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Play,Pause,ExternalLink,Search,MapPin,BookOpen,Layers,ArrowLeft,Maximize2} from 'lucide-react';
import TerrainMap from '@/components/atlas/terrain-map';
import {overlaps,type Atlas,type Specimen} from '@/lib/atlas';

function Link({url,children}:{url:string;children:React.ReactNode}){return <a href={url} target="_blank" rel="noreferrer">{children}<ExternalLink size={13}/></a>}
export default function Home(){
 const [data,setData]=useState<Atlas|null>(null),[error,setError]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[variant,setVariant]=useState('all'),[facet,setFacet]=useState('all'),[query,setQuery]=useState(''),[region,setRegion]=useState('all'),[year,setYear]=useState(720),[all,setAll]=useState(true),[playing,setPlaying]=useState(false),[view,setView]=useState('atlas'),[lightbox,setLightbox]=useState<Specimen|null>(null),[imageIndex,setImageIndex]=useState(0),[focus,setFocus]=useState(0);
 useEffect(()=>{fetch('/data/atlas.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setData(d as Atlas)).catch(()=>setError(true))},[]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setYear(y=>{if(y>=1000){setPlaying(false);return 1000}return y+5}),700);return()=>clearInterval(t)},[playing]);
 const families=useMemo(()=>data?.families.filter(f=>(region==='all'||f.region===region)&&overlaps(f.start,f.end,all?null:year)&&(!query||[f.title,f.zh,f.region,f.description,f.legend||'',...data.specimens.filter(s=>s.familyId===f.id).map(s=>s.title+' '+s.catalogue+' '+s.description+' '+s.facets.join(' ')+' '+s.sources.map(x=>x.label).join(' '))].join(' ').toLowerCase().includes(query.toLowerCase())))||[],[data,query,region,year,all]);
 const selected=data?.families.find(f=>f.id===selectedId)||null;
 const inPeriod=selected?overlaps(selected.start,selected.end,all?null:year):true;
 const specimens=data?.specimens.filter(s=>s.familyId===selectedId)||[];
 const variants=data?.variants.filter(v=>v.familyId===selectedId)||[];
 const facets=Array.from(new Set(specimens.flatMap(s=>s.facets)));
 const shown=specimens.filter(s=>(variant==='all'||(variant==='unassigned'?s.variantId===null:s.variantId===variant))&&(facet==='all'||s.facets.includes(facet)));
 const place=data?.places.find(p=>p.id===selected?.anchor?.placeId);
 function choose(id:string){setSelectedId(id);setVariant('all');setFacet('all');setFocus(f=>f+1);setView('atlas');if(window.matchMedia('(max-width:760px)').matches)requestAnimationFrame(()=>document.querySelector('.detail-panel')?.scrollIntoView({behavior:'smooth',block:'start'}))}
 function open(s:Specimen){setLightbox(s);setImageIndex(0)}
 useEffect(()=>{
 const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!ctx?.registerTool||!data)return;const lifecycle=new AbortController();
 Promise.resolve(ctx.registerTool({name:'set_atlas_year',description:'Filter the atlas by issue date and return matching coin families.',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:500,maximum:1000}},required:['year'],additionalProperties:false},execute:async(input:unknown)=>{const y=(input as {year?:unknown})?.year;if(typeof y!=='number'||!Number.isInteger(y)||y<500||y>1000)throw Error('year must be 500–1000');setYear(y);setAll(false);setPlaying(false);return {year:y,families:data.families.filter(f=>overlaps(f.start,f.end,y)).map(f=>({id:f.id,title:f.title}))}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[data]);
 return <main><header className="site-header"><a className="brand" href="/">◈ <span>SOGDIAN COINS ATLAS<small>粟特钱币 · 空间、时间与实物</small></span></a><nav aria-label="Main navigation">{[['atlas','地图 Atlas'],['vault','探索宝库'],['research','资料与覆盖率']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav></header>
 {!data?<p className="loading" role="status">{error?'Catalogue could not load. Please reload.':'Loading the research atlas…'}</p>:<>
 {view==='atlas'&&<><div className="atlas-filters"><div className="search"><Search size={16}/><input aria-label="Search coin families, catalogue numbers and Zeno IDs" placeholder="搜索类型、铭文或编号 / e.g. Nana, Zeno 81165" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Region" value={region} onChange={e=>setRegion(e.target.value)}><option value="all">All regions · 全部地区</option>{Array.from(new Set(data.families.map(f=>f.region))).map(r=><option key={r}>{r}</option>)}</select><span className="countline">{families.length} 类型家族 · {data.specimens.length} 标本记录</span></div>
 <div className="atlas-layout"><section className="map-column"><TerrainMap data={data} families={families} selected={inPeriod?selected:null} onSelect={choose} year={all?null:year} focus={focus}/><div className="timeline"><button className="play" aria-label={playing?'Pause timeline':'Play timeline'} onClick={()=>{setAll(false);if(year>=1000)setYear(500);setPlaying(p=>!p)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><strong>{all?'All periods':`${year} CE`}</strong><div className="slider-box"><Slider aria-label="Historical year" min={500} max={1000} step={5} value={[year]} onValueChange={([y])=>{setYear(y);setAll(false);setPlaying(false)}}/><div className="ticks"><span>500</span><span>750</span><span>1000 CE</span></div></div><button className={all?'period active':'period'} onClick={()=>{setAll(a=>!a);setPlaying(false)}}>全部时期</button></div><p className="timeline-note">时间轴筛选发行年代区间；争议年代保留在“全部时期”。地图照片的位置表示注明的展示锚点。</p>
 <div className="family-list"><div className="section-caption"><span>MAJOR TYPES / 类型家族</span><span>{families.length} in selection</span></div><div className="family-grid">{families.map(f=><button key={f.id} className={'family-card'+(f.id===selectedId?' selected':'')} onClick={()=>choose(f.id)}><img src={f.image} alt={f.title} loading="lazy"/><span><strong>{f.title}</strong><small>{f.region} · {f.dateLabel}</small><em>{data.specimens.filter(s=>s.familyId===f.id).length} 标本 · {data.variants.filter(v=>v.familyId===f.id).length} 细分组</em></span></button>)}{!families.length&&<p className="empty">当前条件没有匹配的类型。尝试“全部时期”或清除搜索。</p>}</div></div></section>
 <aside className="detail-panel">{selected?<><div className="detail-top"><button className="back" onClick={()=>setSelectedId(null)}><ArrowLeft size={14}/>全部类型</button><span className="eyebrow">TYPE FAMILY</span></div><h1>{selected.title}</h1><p className="chinese-title">{selected.zh}</p><p className="date">{selected.dateLabel} · {selected.region}</p>{!inPeriod&&<p className="notice">此类型不在当前年份范围内；图库保持打开，地图已隐藏其图层。</p>}<p>{selected.description}</p><div className="anchor-info"><MapPin size={17}/><div><strong>{place?.name||'地域待定'}</strong><span>{selected.anchor?.role||'Unassigned'} · {place?.precision||'待考'}</span><p>{selected.anchor?.note||'暂不设置地图坐标。'}</p></div></div>
 <div className="hierarchy"><span>主类型</span><i>→</i><span>细分组</span><i>→</i><span>特征筛选</span><i>→</i><span>实物标本</span></div>
 <div className="gallery-heading"><h2>细分图库</h2><span>{specimens.length} 标本 / {specimens.reduce((n,s)=>n+s.images.length,0)} 图片</span></div><label className="field-label">目录细分 / Catalogue grouping<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="all">全部细分与待定标本</option>{variants.map(v=><option value={v.id} key={v.id}>{v.title} ({specimens.filter(s=>s.variantId===v.id).length})</option>)}{specimens.some(s=>s.variantId===null)&&<option value="unassigned">细分待定 ({specimens.filter(s=>s.variantId===null).length})</option>}</select></label>{facets.length>0&&<label className="field-label">铭文、Tamgha 与版式<select value={facet} onChange={e=>setFacet(e.target.value)}><option value="all">全部特征</option>{facets.map(f=><option key={f}>{f}</option>)}</select></label>}
 {variant!=='all'&&variant!=='unassigned'&&<p className="muted small">{variants.find(v=>v.id===variant)?.description}</p>}
 <div className="specimen-grid">{shown.map(s=><article className="specimen-card" key={s.id}><button className="photo" onClick={()=>open(s)} aria-label={`Enlarge ${s.title}`}><img src={s.images[0]?.path} alt={s.title+' — obverse and reverse as supplied'} loading="lazy"/><span><Maximize2 size={13}/>{s.images[0]?.width} px</span></button><h3>{s.title}</h3><p>{[s.weightG?`${s.weightG} g`:null,s.diameterMm?`${s.diameterMm} mm`:null].filter(Boolean).join(' · ')||'重量／直径未记录'}</p><small>{s.catalogue||'细分目录号待核'}</small><div className="record-links">{s.sources.filter(x=>x.relation==='same_specimen').slice(0,2).map(x=><Link key={x.url} url={x.url}>{x.label}</Link>)}</div></article>)}</div>{!shown.length&&<p className="empty">当前细分与特征组合尚无标本。</p>}
 <details className="research-details"><summary><BookOpen size={16}/>铭文、证据与研究</summary>{selected.legend&&<><h3>铭文读法</h3><p className="legend-text">{selected.legend}</p><p>{selected.legendNote}</p></>}<h3>地理证据</h3><p>{data.evidence.some(e=>e.familyId===selected.id&&e.kind!=='context')?'已记录的出土地见地图与下列原始来源。':'尚未核定本类型的具体窖藏或出土点。锚点位置不作为流通证据，流通面积保持待补。'}</p>{data.evidence.filter(e=>e.familyId===selected.id).map(e=><p key={e.id}>{e.note}<Link url={e.source}>证据来源</Link></p>)}<h3>论文与目录</h3>{selected.publications.map(p=><div className="reading" key={p.url}><Link url={p.url}>{p.title}</Link><small>{p.role}</small></div>)}{selected.question&&<p className="notice">{selected.question}</p>}<h3>模具研究</h3><p>目前没有经过论证的同模／同范分组。铸造钱币的母模、范及印制关系将以独立证据记录。</p></details>
 </>:<div className="welcome"><Layers size={28}/><h1>从地图进入钱币</h1><p>选择一个钱币家族，查看细分图库、高清标本和原始来源。</p><button className="nana-entry" onClick={()=>choose('lady-nana')}><img src={data.families.find(f=>f.id==='lady-nana')?.image} alt="Lady Nana coin"/><strong>Lady Nana / 娜娜夫人</strong><span>打开类型、细分与标本 →</span></button><div className="coverage-mini"><strong>Lady Nana · Zeno 对照</strong><span>{data.coverage.importedZenoRecords} / {data.coverage.zenoRecordCount??'?'} 分类记录已导入图片</span><small>{data.coverage.images} 张 Lady Nana 图片（含跨来源）；{data.coverage.date} 快照；全项目覆盖仍在扩展。</small></div><p className="small muted">照片锚点旁的数字为当前标本记录数。同城类型按屏幕位置展开，实际地理锚点不变。</p></div>}</aside></div></>}
 {view==='vault'&&<section className="text-page"><span className="eyebrow">EXPLORATION VAULT</span><h1>探索宝库</h1><p>待定归属、争议年代和未完成的细分，保留在同一套可追溯资料中。</p><div className="vault-grid">{data.families.filter(f=>f.status==='exploration').map(f=><article key={f.id}><img src={f.image} alt={f.title}/><h2>{f.title}</h2><p>{f.description}</p><p className="notice">{f.question}</p><button onClick={()=>choose(f.id)}>查看资料与标本 →</button></article>)}</div></section>}
 {view==='research'&&<section className="text-page"><span className="eyebrow">RESEARCH & COVERAGE</span><h1>覆盖到哪里，证据就写到哪里。</h1><p>核心：七河地区及相关粟特方孔钱。这里分别统计分类记录、实物标本、图片和已核定的细分，便于持续对照 Zeno。</p><div className="metrics"><div><strong>{data.families.length}</strong><span>类型家族 / 候选组</span></div><div><strong>{data.specimens.length}</strong><span>标本记录</span></div><div><strong>{data.specimens.reduce((n,s)=>n+s.images.length,0)}</strong><span>实际图片文件</span></div><div><strong>{data.places.length}</strong><span>历史地点</span></div></div><h2>Lady Nana 分类覆盖</h2><p><Link url={data.coverage.categoryUrl}>Zeno 分类 #3106</Link>当前快照记录 {data.coverage.zenoRecordCount??'未核定'} 条；已导入带图记录 {data.coverage.importedZenoRecords} 条。Lady Nana 当前跨来源共 {data.coverage.images} 张图片；全站图片总数由标本图库独立计算。日期：{data.coverage.date}。这项分类记录计数只对应该分类，不代表整个粟特钱币数据库。</p><p>重复记录依来源声明、照片和特征核对。Zeno264408 与 Bactrianumis5898 归于同一标本；Numista197126 与 SARC28/145 归于同一标本。尚未穷尽核定的跨平台重复保留待复核状态，标本记录总数不等同于最终独立实物总数。</p><h2>七河地区 · 来源分类基准</h2><p>Zeno Semirech’e 当前列出 569 条照片记录；其中 11 条直接位于父分类，其余分布于下列子分类。该数字包含尚待审查的记录，不等于 569 枚独立方孔钱。父子分类数量不能重复相加。</p><div className="census-table"><table><thead><tr><th>Zeno 子分类</th><th>照片记录</th><th>Atlas 状态</th></tr></thead><tbody>{data.scopeCensus.filter(c=>c.parent==='2141').map(c=><tr key={c.categoryId}><td><Link url={c.url}>{c.title}</Link></td><td>{c.sourcePhotoCount}</td><td>逐条匹配待完成</td></tr>)}</tbody></table></div><h2>分类规则</h2><p>主类型 / 家族 → 目录定义的 variant → 铭文、Tamgha、符号、版式特征 → 实物。同一个目录号的“ff.”引用暂作为目录细分组；不同著作的编号不自动判为等价。模具／铸范关系另行研究，不把每张照片制造成一个新品种。</p><h2>历史地理</h2><p>城市、遗址与出土点使用不同角色。未找到类型特定出土证据时，以注明的城市或区域中心展示。半透明面积仅接受带来源和含义的几何记录；地理背景、推定分布和已论证流通区分别存储。历史地名位于当代地形底图上；切换“现代地形参考”可放大查看更细地形与现代地名。</p><div className="reading-grid">{[{title:'IICAS · A Catalogue of Sogdian Coin Legends and Countermarks of Central Asia',url:'https://iicas.int/book/177',role:'2024 · 学术分类底本；逐条映射尚在进行'},{title:'Turko-Sogdian Coinage · Larissa Baratova',url:'https://www.iranicaonline.org/articles/turko-sogdian-coinage/',role:'综述与参考文献'},{title:'Panjikant · Boris Marshak',url:'https://www.iranicaonline.org/articles/panjikant/',role:'历史地理与考古背景；Nana 身份解释保留讨论'},{title:'Coins of Central Asia',url:'https://sogdcoins.narod.ru/english/index.html',role:'旧目录分类与实物来源'}].map(p=><article key={p.url}><Link url={p.url}>{p.title}</Link><p>{p.role}</p></article>)}</div><p className="muted">图片保留来源与原始分辨率。对照链接不算已导入图片，销售地点不算出土地。高清图片与旧目录小图并存，图库逐张显示实际尺寸。</p></section>}
 </>}
 <footer><span>SOGDIAN COINS ATLAS</span><span>Research edition · September 2026</span></footer>
 <Dialog open={!!lightbox} onOpenChange={open=>{if(!open)setLightbox(null)}}><DialogContent className="lightbox"><DialogTitle>{lightbox?.title}</DialogTitle><DialogDescription>{lightbox?.images[imageIndex]?.credit} · {lightbox?.images[imageIndex]?.width} × {lightbox?.images[imageIndex]?.height} px · rights: {lightbox?.images[imageIndex]?.rightsStatus}</DialogDescription>{lightbox&&<><div className="lightbox-image"><img src={lightbox.images[imageIndex]?.path} alt={lightbox.title}/></div>{lightbox.images.length>1&&<div className="image-tabs">{lightbox.images.map((im,i)=><button className={imageIndex===i?'active':''} key={im.id} onClick={()=>setImageIndex(i)}>图片 {i+1}</button>)}</div>}<p>{lightbox.description}</p><p>{lightbox.catalogue}</p><div className="record-links">{lightbox.sources.map(s=><Link key={s.url} url={s.url}>{s.label}{s.relation==='comparison'?' · 对照标本':''}</Link>)}{lightbox.images[imageIndex]?.rightsSourceUrl&&<Link url={lightbox.images[imageIndex].rightsSourceUrl!}>来源权利条款</Link>}<a href={lightbox.images[imageIndex]?.path} target="_blank" rel="noreferrer">打开原始像素图片 ↗</a></div></>}</DialogContent></Dialog>
 </main>
}
