"use client";
import {useEffect,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Play,Pause,Plus,Minus,ExternalLink,Compass,BookOpen,ArrowUpRight} from 'lucide-react';

type Coin={id:string;name:string;region:string;start:number|null;end:number|null;dateLabel:string;lat:number|null;lon:number|null;image:string;description:string;source:string;credit:string;reference:string;zeno:string|null;research:string;status:string;question?:string};
type Geo={features:{geometry:{type:string;coordinates:number[][][]|number[][][][]};properties:{name:string}}[]};
const project=([lon,lat]:number[])=>[(lon-49)*23,(49-lat)*30];
const regions=[['SEMIRECHYE',75,44.6],['SOGDIANA',66.7,40.7],['TOKHARISTAN',69,36.6],['XINJIANG',83.8,42.8],['IRAN',55,33.4],['AFGHANISTAN',65,33.7]] as const;
function Map({coins,onSelect,selected}:{coins:Coin[];onSelect:(c:Coin)=>void;selected:string}){
 const [geo,setGeo]=useState<Geo|null>(null),[zoom,setZoom]=useState(1),[offset,setOffset]=useState([0,0]),[error,setError]=useState(false);
 useEffect(()=>{fetch('/data/map.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(setGeo).catch(()=>setError(true))},[]);
 const groups=Object.values(coins.reduce((a,c)=>{if(c.lat===null||c.lon===null)return a;const k=`${c.lon},${c.lat}`;(a[k]??=[]).push(c);return a},{} as Record<string,Coin[]>));
 return <div className="map"><svg viewBox="0 0 1100 690" role="img" aria-label="Regional map of square-holed coinage"><defs><pattern id="grid" width="115" height="150" patternUnits="userSpaceOnUse"><path d="M 115 0 L 0 0 0 150" fill="none" stroke="#ffffff09"/></pattern></defs><rect width="1100" height="690" fill="#0c202a"/><g transform={`translate(${550*(1-zoom)+offset[0]},${345*(1-zoom)+offset[1]}) scale(${zoom})`}>
 {geo?.features.map((f,i)=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates as number[][][]]:f.geometry.coordinates as number[][][][];return <path key={i} d={polys.map(p=>p.map(r=>r.map((v,j)=>(j?'L':'M')+project(v).join(',')).join(' ')+'Z').join(' ')).join(' ')} fill="#19343c" stroke="#597373" strokeWidth=".65"/>})}
 <rect width="1100" height="690" fill="url(#grid)"/>
 {regions.map(([name,lon,lat])=>{const [x,y]=project([lon,lat]);return <text key={name} x={x} y={y} className="region-label">{name}</text>})}
 {groups.map(g=>{const [x,y]=project([g[0].lon!,g[0].lat!]);return <g key={g[0].id}>{g.map((c,i)=>{const dx=(i-(g.length-1)/2)*42,dy=i%2===0?0:42;return <g key={c.id} transform={`translate(${x+dx},${y+dy})`} tabIndex={0} role="button" aria-label={c.name} onClick={()=>onSelect(c)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(c)}}} className="map-coin"><line x1="0" y1="0" x2={-dx} y2={-dy+35} stroke="#dbb46a" strokeWidth="1"/><circle r="24" fill="#10212b" stroke={selected===c.id?'#f6df9b':'#ad8a4f'} strokeWidth={selected===c.id?3:1}/><clipPath id={'clip-'+c.id}><circle r="21"/></clipPath><image href={c.image} x="-22" y="-21" width="84" height="42" preserveAspectRatio="xMinYMid slice" clipPath={`url(#clip-${c.id})`}/><title>{c.name} · {c.dateLabel}</title></g>})}</g>})}
 </g></svg><div className="map-top"><span className="eyebrow">THE REGIONAL ATLAS</span><span>{coins.length} candidate records in view</span></div><div className="map-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(3,z+.25))}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><Minus size={18}/></button><button aria-label="Reset map" onClick={()=>{setZoom(1);setOffset([0,0])}}><Compass size={18}/></button></div><div className="pan-controls" aria-label="Move map">{[['←',-100,0],['↑',0,-100],['↓',0,100],['→',100,0]].map(([label,x,y])=><button key={label} aria-label={`Pan ${label}`} onClick={()=>setOffset(o=>[o[0]+Number(x),o[1]+Number(y)])}>{label}</button>)}</div><div className="map-note">Regional anchors · approximate attribution, not findspots<br/><a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a> · modern boundaries for orientation</div>{error&&<div className="map-error">The basemap could not load. Coin locations remain available.</div>}</div>
}
export default function Home(){
 const [coins,setCoins]=useState<Coin[]>([]),[selected,setSelected]=useState<Coin|null>(null),[year,setYear]=useState(750),[all,setAll]=useState(true),[playing,setPlaying]=useState(false),[lightbox,setLightbox]=useState(false),[loadError,setLoadError]=useState(false);
 useEffect(()=>{fetch('/data/coins.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setCoins(d);setSelected(d[0]??null)}).catch(()=>setLoadError(true))},[]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setYear(y=>{if(y>=1000){setPlaying(false);return 1000}return y+10}),800);return()=>clearInterval(timer)},[playing]);
 useEffect(()=>{
 const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
 if(!ctx?.registerTool)return;
 const lifecycle=new AbortController();
 Promise.resolve(ctx.registerTool({name:'set_atlas_year',description:'Set the visible atlas year and return matching types.',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:500,maximum:1000}},required:['year'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const y=(input as {year?:unknown})?.year;if(typeof y!=='number'||!Number.isInteger(y)||y<500||y>1000)throw new Error('year must be an integer from 500 through 1000');setYear(y);setAll(false);setPlaying(false);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {year:y,types:coins.filter(c=>c.lat!==null&&c.start!==null&&c.end!==null&&c.start<=y&&c.end>=y).map(c=>({id:c.id,name:c.name}))}}},{signal:lifecycle.signal})).catch(()=>{});
 return()=>lifecycle.abort();
 },[coins]);
 const mapped=coins.filter(c=>c.lat!==null&&c.lon!==null);const visible=mapped.filter(c=>all||(c.start!==null&&c.end!==null&&c.start<=year&&c.end>=year));const vault=coins.filter(c=>c.status!=='mapped');
 function choose(c:Coin){setSelected(c)}
 return <main><header><a className="brand" href="/">◈ <span>SOGDIAN<span className="brand-sub">COINS ATLAS</span></span></a><p>Square-holed coinage across Central Asia</p><span className="edition">RESEARCH EDITION · 01</span></header><div className="intro"><div><span className="eyebrow">SEVEN RIVERS & BEYOND</span><h1>A small coin.<br/><em>A wider world.</em></h1></div><p>Explore coins across place and time.<br/>Follow their inscriptions, symbols and<br className="desktop"/> the questions they leave behind.</p></div>
 <Tabs defaultValue="atlas"><div className="tab-row"><TabsList variant="line"><TabsTrigger value="atlas"><Compass size={17}/>Atlas / 地图</TabsTrigger><TabsTrigger value="vault">Exploration vault / 探索宝库 <span className="count">{vault.length}</span></TabsTrigger><TabsTrigger value="sources"><BookOpen size={17}/>Research / 文献</TabsTrigger></TabsList><span className="secondary">Semirechye · Sogdiana · Tokharistan · Xinjiang</span></div>
 <TabsContent value="atlas"><div className="workspace"><section><Map coins={visible} onSelect={choose} selected={selected?.id??''}/><div className="timeline"><div className="timeline-head"><button className="play" aria-label={playing?'Pause timeline':'Play timeline'} onClick={()=>{setAll(false);if(year>=1000)setYear(500);setPlaying(p=>!p)}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><strong>{all?'All periods':`${year} CE`}</strong><span className="secondary">Candidate records whose date ranges overlap this year</span><button className={all?'period active':'period'} onClick={()=>{setAll(a=>!a);setPlaying(false)}}>All periods</button></div><Slider aria-label="Historical year" min={500} max={1000} step={10} value={[year]} onValueChange={([y])=>{setYear(y);setAll(false);setPlaying(false)}}/><div className="ticks">{[500,600,700,800,900,1000].map(y=><span key={y}>{y}</span>)}</div></div><div className="coin-strip">{visible.map(c=><button key={c.id} className={selected?.id===c.id?'mini selected':'mini'} onClick={()=>choose(c)}><img src={c.image} alt={c.name}/><span>{c.name}<small>{c.dateLabel}</small></span></button>)}{!visible.length&&<p>No catalogued types overlap this year in the current research selection.</p>}</div></section><aside className="detail">{selected?<><span className="eyebrow">{selected.region}</span><h2>{selected.name}</h2><p className="date">{selected.dateLabel} <span> · Copper alloy</span></p><button className="specimen" onClick={()=>setLightbox(true)} aria-label="Enlarge specimen photograph"><img src={selected.image} alt={`${selected.name}, source specimen photograph`}/><span>View image <ArrowUpRight size={16}/></span></button><p className="credit">{selected.credit}</p><p>{selected.description}</p><dl><div><dt>Catalogue</dt><dd>{selected.reference}</dd></div><div><dt>Location</dt><dd>{selected.lat!==null?'Approximate regional attribution':'Attribution under study'}</dd></div></dl>{selected.question&&<div className="question"><span className="eyebrow">OPEN QUESTION</span><p>{selected.question}</p></div>}<div className="source-links"><a href={selected.source} target="_blank" rel="noreferrer">Specimen & attribution source <ExternalLink size={15}/></a>{selected.zeno?<a href={selected.zeno} target="_blank" rel="noreferrer">Zeno catalogue cross-reference <ExternalLink size={15}/></a>:<p className="secondary">Zeno record: matching in progress</p>}<a href={selected.research} target="_blank" rel="noreferrer">Related research & catalogue <ExternalLink size={15}/></a></div></>:<p>{loadError?'The catalogue could not load. Please reload the page.':'Loading the research catalogue…'}</p>}</aside></div></TabsContent>
 <TabsContent value="vault"><section className="vault-intro"><span className="eyebrow">EXPLORATION VAULT</span><h2>Questions worth keeping open.</h2><p>Uncertain origins, revised dates and unusual forms. Each entry preserves its source and the question still to be resolved.</p></section><div className="vault-grid">{vault.map(c=><article key={c.id}><img src={c.image} alt={c.name}/><span className="eyebrow">{c.region}</span><h3>{c.name}</h3><p>{c.description}</p><div className="question">{c.question}</div><a href={c.source} target="_blank" rel="noreferrer">Inspect the source <ExternalLink size={15}/></a>{c.zeno&&<a href={c.zeno} target="_blank" rel="noreferrer">Zeno cross-reference <ExternalLink size={15}/></a>}<a href={c.research} target="_blank" rel="noreferrer">Related research <ExternalLink size={15}/></a><small>{c.credit}</small></article>)}</div></TabsContent>
 <TabsContent value="sources"><section className="research"><span className="eyebrow">THE RESEARCH DESK</span><h2>A catalogue that can keep growing.</h2><p>This interaction draft contains 12 specimen records, provisionally linked to candidate types. Their classification against IICAS 2024 remains to be reviewed. Coverage is in progress: Afghanistan requires specimen-level review; Xinjiang currently has one comparative record. The atlas does not yet represent a complete census of types.</p><div className="reading-grid"><article><span>01 · FOUNDATION · 2024</span><h3>A Catalogue of Sogdian Coin Legends and Countermarks of Central Asia</h3><p>Begmatov, Boboyorov, Goyibov, Kulish, Lurje & Naymark. IICAS. 496 pages. A regional framework for inscriptions, chronology and research history.</p><a href="https://iicas.int/book/177" target="_blank" rel="noreferrer">Publication & download <ExternalLink size={15}/></a></article><article><span>02 · SEMIRECHYE</span><h3>The Early Mediaeval Coin Complex from Semirechye</h3><p>A. M. Kamyshev. A foundational catalogue for the Türgesh and related series. Legacy attributions are retained as source claims pending comparison with later work.</p><a href="https://www.charm.ru/kamyshev.shtml" target="_blank" rel="noreferrer">Read the catalogue overview <ExternalLink size={15}/></a></article><article><span>03 · CONTEXT</span><h3>Turko-Sogdian coinage</h3><p>Encyclopaedia Iranica. An introduction to the coin families and the use of Sogdian inscriptions.</p><a href="https://www.iranicaonline.org/articles/turko-sogdian-coinage/" target="_blank" rel="noreferrer">Read the overview <ExternalLink size={15}/></a></article><article><span>04 · TRADE & CIRCULATION</span><h3>The place of coins on the Silk Road</h3><p>Valerie Hansen. A study of coins and other forms of money, available in Chinese through Yale University.</p><a href="https://history.yale.edu/sites/default/files/files/Hansen%20Place%20of%20Coins%20%28Chi%29.pdf" target="_blank" rel="noreferrer">Read the paper <ExternalLink size={15}/></a></article></div><h3>Reading this atlas</h3><p>Map anchors indicate approximate regions of attribution; they do not claim a mint or archaeological findspot. The timeline shows overlapping date ranges, rather than proven circulation in every intervening year. Zeno links are catalogue cross-references reported by the cited source, unless independently verified.</p><p>Photographs remain credited to their original sources. Source image resolution varies; most are catalogue thumbnails. The relational research schema is drafted separately; this interface still uses an initial display dataset. New specimens and changed attributions can be added without overwriting earlier research questions.</p></section></TabsContent></Tabs>
 <footer><span>SOGDIAN COINS ATLAS</span><p>An independent numismatic research project · Inspired by conversations at the Vancouver coin club</p><span>Interaction draft · September 2026</span></footer>
 <Dialog open={lightbox} onOpenChange={setLightbox}><DialogContent className="lightbox"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.credit} · Original available resolution</DialogDescription>{selected&&<img src={selected.image} alt={selected.name}/>}<a href={selected?.source} target="_blank" rel="noreferrer">View the original source</a></DialogContent></Dialog>
 </main>
}
