"""Offline Bregel map-15 registration. Standard library only; no network/export of Atlas."""
import json, math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
source=json.loads((ROOT/'docs/reviews/T21/qara-khitai-study/source-trace.json').read_text())
places={p['id']:p for p in json.loads((ROOT/'public/data/atlas.json').read_text())['places']}
# LCC intermediate plane, 30/60 standard parallels, 75E central meridian.
r=math.radians
n=math.log(math.cos(r(30))/math.cos(r(60)))/math.log(math.tan(math.pi/4+r(60)/2)/math.tan(math.pi/4+r(30)/2))
f=math.cos(r(30))*math.tan(math.pi/4+r(30)/2)**n/n

def project(ll):
 lon,lat=map(r,ll);rho=f/math.tan(math.pi/4+lat/2)**n;theta=n*(lon-r(75))
 return [rho*math.sin(theta),-rho*math.cos(theta)]
def inverse(x,y):
 rho=math.hypot(x,y)
 return [math.degrees(math.atan2(x,-y)/n)+75,math.degrees(2*math.atan((f/rho)**(1/n))-math.pi/2)]
def solve(a,b):
 a=[list(row)+[v] for row,v in zip(a,b)]
 for i in range(len(b)):
  pivot=max(range(i,len(b)),key=lambda j:abs(a[j][i]));a[i],a[pivot]=a[pivot],a[i]
  v=a[i][i];a[i]=[x/v for x in a[i]]
  for j in range(len(b)):
   if j!=i:
    v=a[j][i];a[j]=[x-v*y for x,y in zip(a[j],a[i])]
 return [row[-1] for row in a]
# Fit source-page coordinates to geographic intermediate plane.
rows=[[1,*c['page']] for c in source['controls']]
normal=[[sum(v[i]*v[j] for v in rows) for j in range(3)] for i in range(3)]
target=[project(places[c['placeId']]['coordinates']) for c in source['controls']]
coef=[solve(normal,[sum(v[i]*q[axis] for v,q in zip(rows,target)) for i in range(3)]) for axis in range(2)]
def xy(p):return [sum(a*b for a,b in zip(c,[1,*p])) for c in coef]
def ll(p):return [round(v,5) for v in inverse(*xy(p))]
def flatten(path):
 out=[]
 for cmd in path:
  op,*v=cmd
  if op=='m':out.append(v[0])
  elif op=='l':out.append(v[0])
  elif op in ['c','v','y']:
   a=out[-1]
   if op=='v':v=[a,*v]
   if op=='y':v=[*v,v[-1]]
   b,c,d=v
   # Samples evaluate the SOURCE cubic, not invented jitter/smoothing.
   for i in range(1,9):
    t=i/8;s=1-t
    out.append([s**3*a[k]+3*s*s*t*b[k]+3*s*t*t*c[k]+t**3*d[k] for k in [0,1]])
  elif op=='h':out.append(out[0])
 return out
paths={k:flatten(v) for k,v in source['paths'].items()}
a,b,c=paths['westNorth'],paths['south'],paths['northEast'];lake=paths['lakeShore']
# Original strokes overlap at the right page edge. Trim inside their 1.8pt stroke
# envelope to one common coverage cut; this seam is NOT a political boundary.
cut=1048.0
def clip(path):
 out=[]
 for i,p in enumerate(path):
  if i and (path[i-1][0]-cut)*(p[0]-cut)<0:
   q=path[i-1];t=(cut-q[0])/(p[0]-q[0]);out.append([cut,q[1]+t*(p[1]-q[1])])
  if p[0]<=cut:out.append(p)
 return out
b,c=clip(b),clip(c)
def nearest(p):return min(range(len(lake)),key=lambda i:sum((x-y)**2 for x,y in zip(p,lake[i])))
i,j=nearest(a[-1]),nearest(c[-1]);loop=lake[:-1] if lake[0]==lake[-1] else lake
# Choose southern shore (larger mean page y), preserve actual lake contour.
arcs=[]
for step in [1,-1]:
 arc=[];k=i
 while True:
  arc.append(loop[k])
  if k==j:break
  k=(k+step)%len(loop)
 arcs.append(arc)
shore=max(arcs,key=lambda arc:sum(p[1] for p in arc)/len(arc))
ring=a+shore+list(reversed(c))+list(reversed(b))+[a[0]]
report=[]
for control in source['controls']:
 actual=places[control['placeId']]['coordinates'];got=ll(control['page'])
 dx=(got[0]-actual[0])*111.2*math.cos(r(actual[1]));dy=(got[1]-actual[1])*111.2
 report.append({'placeId':control['placeId'],'sourcePage':control['page'],'existingAtlasCoordinate':actual,'registered':got,'residualKm':round(math.hypot(dx,dy),1)})
result={'geometry':{'type':'Polygon','coordinates':[[ll(p) for p in ring]]},'boundary':{'type':'MultiLineString','coordinates':[[ll(p) for p in path] for path in [a,b,c]]},'coverageEdge':{'type':'LineString','coordinates':[ll(c[0]),ll(b[-1])]},'coverageLabel':ll([1030,415]),'registration':{'method':'LCC intermediate (30N/60N, 75E) + least-squares affine page registration; not a claim about original projection','coefficients':coef,'controls':report,'maxResidualKm':max(x['residualKm'] for x in report)}}
(ROOT/'lib/qara-khitai-geometry.ts').write_text('// Generated by scripts/build-qara-khitai-sample.py; Bregel 2003 map 15, p.31.\nexport const qaraKhitaiGeometry = '+json.dumps(result,ensure_ascii=False,separators=(',',':'))+';\n')
(ROOT/'docs/reviews/T21/qara-khitai-study/registration.json').write_text(json.dumps(result['registration'],ensure_ascii=False,indent=2)+'\n')
print(json.dumps(result['registration'],ensure_ascii=False,indent=2))
