'use client';
import {layerNames,roleNames,periodLabel,rangeColor,type LayerKey,type LayerSettings,type MapBackground,type MapRange,type SymbolRole} from '@/lib/map-layers';
import {symbolUrl} from '@/lib/map-symbols';
const groups:{title:string;keys:LayerKey[]}[]=[{title:'钱币',keys:['coins']},{title:'历史地点',keys:['cities','centers','sites','mints']},{title:'发现与历史范围',keys:['findspots','hoards','polities','circulation','context']}];
const roles={cities:'city',centers:'center',sites:'site',mints:'mint-candidate',findspots:'findspot',hoards:'hoard'} as const;
export default function MapLayerPanel({base,effective,setBase,background,ranges,renderedRoles,versions,setVersion}:{base:LayerSettings;effective:LayerSettings;setBase:(s:LayerSettings)=>void;background:MapBackground;ranges:MapRange[];renderedRoles:SymbolRole[];versions:Record<string,string>;setVersion:(object:string,id:string)=>void}){
 return <details className="history-controls"><summary>图层与图例 <small>LAYERS</small></summary><div className="history-controls-scroll">{groups.map(g=><fieldset key={g.title}><legend>{g.title}</legend>{g.keys.map(k=>{const role=k in roles?roles[k as keyof typeof roles]:undefined;const count=k==='coins'?null:k==='polities'?background.ranges.filter(r=>r.kind==='polity'&&r.geometry).length:(k==='circulation'||k==='context')?background.ranges.filter(r=>r.kind===k&&r.geometry).length:background.places.filter(p=>k==='cities'||p.claims.some(c=>c.role===role||(k==='mints'&&c.role==='mint'))).length;return <label key={k}><input type="checkbox" checked={base[k]} onChange={e=>setBase({...base,[k]:e.target.checked})}/>{role?<img src={symbolUrl(role)} alt=""/>:<i className={`layer-swatch ${k}`}/>}<span>{layerNames[k]}{count===0&&<small>暂无对应数据{ k==='polities'?' · 范围待补':''}</small>}{effective[k]&&!base[k]&&<small>当前家族临时背景</small>}</span></label>})}</fieldset>)}
 <section className="active-legend"><strong>当前图例</strong>{renderedRoles.map(role=><span key={role}><img src={symbolUrl(role)} alt=""/>{roleNames[role]}</span>)}{effective.coins&&<span><i className="layer-swatch coins"/>币图／集合 · 角标为匹配家族数</span>}{ranges.map(r=><span key={r.id}><i className={`range-swatch ${r.precision} ${r.kind}`} style={{color:rangeColor(r.objectId)}}/>{r.title} · {r.precision==='approximate'?'大致边缘':'资料边界'}</span>)}{!Object.values(effective).some(Boolean)&&<small>所有图层已关闭；筛选计数保持。</small>}</section>
 {Array.from(new Set(background.ranges.filter(r=>r.geometry).map(r=>r.objectId))).map(id=>{const choices=background.ranges.filter(r=>r.objectId===id&&r.geometry);return choices.length>1?<label key={id}>范围时期<select aria-label={`范围时期 ${choices[0].title}`} value={versions[id]||''} onChange={e=>setVersion(id,e.target.value)}><option value="">请选择时期（不合并范围）</option>{choices.map(r=><option key={r.id} value={r.id}>{r.title} · {periodLabel(r)}</option>)}</select></label>:null})}
 <small>图层只改变地图显示。展示锚点不等于铸币地或出土地；范围年份独立于钱币年代。</small>
 </div></details>
}
