import {layerAvailability} from '@/lib/layer-availability';
'use client';
import {useCopy,useLanguage} from './language';
import type {CopyKey} from '@/lib/i18n';
import {focusReturn} from '@/lib/keyboard';
import ArtIcon from '@/components/visual/ArtIcon';
import {useRef,useEffect} from 'react';
import {layerNames,roleNames,rangeColor,type LayerKey,type LayerSettings,type MapBackground,type MapRange,type SymbolRole,type MapTime} from '@/lib/map-layers';
import {symbolUrl} from '@/lib/map-symbols';
import {rangeName,rangePeriodCopy} from '@/lib/range-copy';
import {historicalRangeViews} from '@/lib/range-time';
import RangeControls,{type RangeControl} from './range-controls';
const groups:{title:string;keys:LayerKey[]}[]=[{title:"钱币",keys:['coins']},{title:"历史地点",keys:['cities','centers','sites','mints']},{title:"发现与历史范围",keys:['findspots','hoards','polities','circulation','context']}];
const roles={cities:'city',centers:'center',sites:'site',mints:'mint-candidate',findspots:'findspot',hoards:'hoard'} as const;
export default function MapLayerPanel({zoom=0,object,onObject,objectName,base,effective,setBase,background,ranges,renderedRoles,time,control,basemap='historical',onHistorical}:{basemap?:string;onHistorical?:()=>void;zoom?:number;object?:string;onObject?:(id:string)=>void;objectName?:(id:string)=>string;base:LayerSettings;effective:LayerSettings;setBase:(s:LayerSettings)=>void;background:MapBackground;ranges:MapRange[];renderedRoles:SymbolRole[];time:MapTime;control:RangeControl}){
 const tr=useCopy(),{locale}=useLanguage();
 const panel=useRef<HTMLDetailsElement>(null);
 const syncCovered=()=>{const media=matchMedia('(max-width:760px), (max-width:1000px) and (max-height:500px)');panel.current?.closest('.atlas-screen,.preview-stage')?.querySelectorAll<HTMLElement>('.family-drawer,.atlas-search-panel,.map-toolbar,.timeline-floating,.terrain-map').forEach(el=>{el.inert=media.matches&&!!panel.current?.open})};
 useEffect(()=>{const media=matchMedia('(max-width:760px), (max-width:1000px) and (max-height:500px)');media.addEventListener('change',syncCovered);return ()=>media.removeEventListener('change',syncCovered)},[]);
 return <details ref={panel} className="history-controls" onToggle={e=>{const stage=e.currentTarget.closest('.atlas-screen,.preview-stage');stage?.classList.toggle('layers-expanded',e.currentTarget.open);syncCovered();if(e.currentTarget.open)panel.current?.querySelector<HTMLButtonElement>('.history-panel-head button')?.focus({preventScroll:true})}}><summary aria-label={tr("图层与图例")}><ArtIcon className="mobile-control-icon" name="layers" size={21}/><span className="desktop-control-label">{tr('图层与图例')}</span></summary><div className="history-panel-head"><strong>{tr("图层设置")}</strong><button aria-label={tr("关闭图层设置")} onClick={()=>{if(panel.current){panel.current.open=false;requestAnimationFrame(()=>{const drawer=document.querySelector('.atlas-screen .family-drawer[data-sheet-state=reading]');const target=drawer?.querySelector<HTMLButtonElement>('.family-title>button')||panel.current?.querySelector('summary');focusReturn(target||null)})}}}>{tr("完成 · 关闭")}</button></div><div className="history-controls-scroll">{groups.map(g=><fieldset key={g.title}><legend>{tr(g.title as CopyKey)}</legend>{g.keys.map(k=>{const role=k in roles?roles[k as keyof typeof roles]:undefined;const {available:count,active}=layerAvailability(k,background,ranges,time);return <label key={k}><input type="checkbox" disabled={count===0} checked={count===0?false:base[k]} onChange={e=>setBase({...base,[k]:e.target.checked})}/>{role?<img src={symbolUrl(role,zoom)} alt=""/>:<i className={`layer-swatch ${k}`}/>}<span>{tr(layerNames[k])}{count===0&&<small>{tr('资料待补')}{ k==='polities'?' · '+tr('范围待补'):''}</small>}{count>0&&k==='polities'&&basemap!=='historical'&&<small>{tr('需历史地图')}</small>}{count>0&&effective[k]&&active===0&&<small>{tr('当前条件无匹配')}</small>}{effective[k]&&!base[k]&&<small>{tr("当前家族临时背景")}</small>}</span></label>})}</fieldset>)}
 {basemap!=='historical'&&<button onClick={onHistorical}>{tr('切换到历史地图')}</button>}<p>{tr('核心地点包含方向识别用的遗址；考古遗址可单独显示。')}</p>{time.mode==='year'&&!ranges.some(r=>r.kind==='polity')&&<p>{tr('该年份的政权范围资料待补；可主动查看历史背景。')}</p>}
 <section className="active-legend"><strong>{tr("当前图例")}</strong>{renderedRoles.map(role=><span key={role}><img src={symbolUrl(role,zoom)} alt=""/>{tr(roleNames[role] as CopyKey)}</span>)}{effective.coins&&<span><i className="layer-swatch coins"/>{tr("币图／集合 · 角标为匹配家族数")}</span>}{ranges.map(r=><span key={r.id}><i className={`range-swatch ${r.precision} ${r.kind}`} style={{color:rangeColor(r.objectId)}}/><span>{rangeName(r,locale)} · {r.kind==='context'?tr("地域边缘 · 点线"):r.precision==='approximate'?tr("大致范围 · 虚线"):r.kind==='polity'?tr("政权边界（原图所绘）"):tr("资料范围边缘")}<small>{rangePeriodCopy(r,locale)}<br/>{r.presentation?.background?tr("历史背景"):null}</small></span></span>)}{!Object.values(effective).some(Boolean)&&<small>{tr("所有图层已关闭；筛选计数保持。")}</small>}</section>
 {onObject&&<label>{tr('范围资料目录')}<select aria-label={tr('范围资料目录')} value={object||''} onChange={e=>onObject(e.target.value)}><option value="">{tr('全部范围资料')}</option>{historicalRangeViews(background.ranges.filter(r=>r.geometry||r.objectId===object),time,control.selection.versions).map(v=><option key={v.objectId} value={v.objectId}>{rangeName(v.selected||v.choices[0],locale,objectName?.(v.objectId))}</option>)}</select></label>}
 <RangeControls enabled={r=>r.kind==='polity'?base.polities:effective[r.kind]} blocked={r=>r.kind==='polity'&&basemap!=='historical'?tr('需历史地图'):''} ranges={background.ranges.filter(r=>r.geometry&&(!object||r.objectId===object))} time={time} control={{...control,setVersion:(id,version)=>{onObject?.(id);control.setVersion(id,version)},setBackground:(id,value)=>{if(value){onObject?.(id);const range=background.ranges.find(r=>r.objectId===id);if(range)setBase({...base,[range.kind==='polity'?'polities':range.kind]:true})}control.setBackground(id,value)}}}/>
 <small>{tr("图层只改变地图显示。展示锚点不等于铸币地或出土地；范围年份独立于钱币年代。")}</small>
 </div></details>
}
